### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by MARTESING** [muzikr/Shapleypy#22]
There are tree generator that should be implemented:

1) Random game
- each value should be set uniformly randomly from a given interval (default interval [0,1])

2) Supermodular (convex games)
- using the same approach as Filip

3) Positive (totally monotonic games)
- these games are defined as non-negative combinations of unanimity games (see https://kam.mff.cuni.cz/~cerny/data/CG/CG4-shapleyho-hodnota_handout.pdf slide 10 for their definition)
- every coeficient should be then taken uniformly randomly from interval [0,1]

For all of the classes, there should be a possibility of normalization:

A) Dividing the game by the value of the grand coalition (evectively setting it to v(N)=1)

B) 0-1-normalization
- for each coalition S, subtract the value of all of its singletons (singletons are now 0)
- divide all the value by v(N) (grandcoalition is now 1)

Other classes to generate:

4) k-games (k a parameter from 1 to n)
- only coefficients of unanimity games u_T where size k is the size of T are non-zero (drawn from interval, by default [0,1] the rest is set to 0)

5) k-additive games
- only coefficients of unanimity games u_T where k is the maximal size of T (so all up to the size) are non-zero (drawn from interval, by default [0,1], the rest is set to 0).

Generators 4) and 5) are not a priority but I think that once we have generator 3), these two are going to be super easy and if supermodularity fails, these are a good extension of the library.

**Comment by muzikr** [comment]
The 4) and 5) should be implemented together with the checkers.

**Comment by muzikr** [comment]
Added in #27 and #24
